import { 
  Shield, 
  Search, 
  Terminal, 
  AlertTriangle, 
  Fingerprint, 
  Bug, 
  Zap, 
  Cloud, 
  Network, 
  Newspaper,
  Barcode,
  ClipboardType,
  Printer,
  Signature,
  Hand,
  Nfc
} from 'lucide-react';

export const CONTENT_DATA = [
  { 
    id: 0, 
    short: "FINGERPRINT_442", 
    title: "Fingerprint 4-4-2", 
    subtitle: "SCAN 4 JARI KANAN, 4 KIRI, 2 JEMPOL", 
    description: "Memaksimalkan efisiensi Enrollment melalui pemindaian 4-4-2 yang presisi. Sistem ini mendukung Matching 1:1 untuk verifikasi identitas instan, serta Matching 1:N (Identification) untuk pencarian data masif dalam basis data biometrik yang kompleks secara real-time.", 
    bgType: 'matrix', 
    tag: "Manual Testing", 
    // Icon: Shield,
    Icon: Fingerprint, 
    status: "Sistem Sidik Jari",
    image: "https://4kwallpapers.com/images/walls/thumbs_3t/9792.jpg" 
  },
  { 
    id: 1, 
    short: "DOKUMEN_SCANNER A4", 
    title: "Document Scanner A4", 
    subtitle: "LAYANAN PEMINDAIAN DOKUMEN A4", 
    description: "Transformasi dokumen fisik ke format digital secara instan. Dilengkapi teknologi OCR mutakhir untuk ekstraksi teks otomatis serta kemudahan untuk pembacaan Barcode/QRCode.", 
    bgType: 'grid', 
    tag: "Automated Scanning", 
    Icon: Search, 
    status: "Sistem Pemindai Dokumen A4",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 2, 
    short: "PASSPORT_SCANNER", 
    title: "Passport Scanner", 
    subtitle: "EKSTRAKSI DATA PASSPORT BERSTANDAR ICAO", 
    description: "pengambilan data dari zona MRZ dan chip RFID paspor secara akurat mendukung standar ICAO. Dilengkapi teknologi pemindaian multispektral untuk memvalidasi fitur keamanan paspor dan memastikan integritas data identitas pemegang dokumen.", 
    bgType: 'pulse', 
    tag: "Security Audit", 
    status: "Sistem Pemindai Dokumen Passport",
    Icon: Newspaper, 
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 3, 
    short: "BARCODE_SCANNER", 
    title: "Barcode Scanner", 
    subtitle: "PEMBACA BARCODE 1D/2D & QRCODE", 
    description: "Tingkatkan produktivitas dengan teknologi pemindaian barcode 1D dan 2D (QR Code) yang responsif. Mampu membaca kode yang rusak atau buram dengan cepat untuk efisiensi manajemen inventaris dan transaksi.", 
    bgType: 'matrix', 
    tag: "Human Defense", 
    Icon: Barcode, 
    status: "Sistem Pemindai Barcode",
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 4, 
    short: "OCR_SCANNER", 
    title: "OCR Scanner", 
    subtitle: "EKSTRAKSI TEKS & DATA DIGITAL", 
    description: "Konversikan dokumen statis menjadi data digital yang dinamis. Teknologi OCR kami mengenali karakter dari berbagai jenis font dan dokumen secara akurat, memungkinkan pencarian teks otomatis dan pemrosesan data tanpa input manual.", 
    bgType: 'grid', 
    tag: "Evidence Recovery", 
    Icon: ClipboardType, 
    status: "Sistem Pengenalan Karakter Optik",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 5, 
    short: "THERMAL_PRINTER", 
    title: "Thermal Printer", 
    subtitle: "PENCETAKAN STRUK TANPA TINTA", 
    description: "Integrasikan sistem dengan pencetakan otomatis melalui koneksi yang stabil. Dirancang untuk durabilitas tinggi dalam mencetak barcode, QR code, hingga manifes pengiriman secara presisi di berbagai kondisi operasional.", 
    bgType: 'pulse', 
    tag: "Threat Intel", 
    Icon: Printer, 
    status: "Sistem Pencetakan Thermal",
    image: "https://i.pinimg.com/originals/a4/b7/e6/a4b7e69536c034f063ac40635e9c62a0.gif" 
  },
  { 
    id: 6, 
    short: "SIGN_PAD", 
    title: "Sign Pad", 
    subtitle: "Digital Signature & Authentication", 
    description: "Tangkap tanda tangan digital dengan akurasi tekanan dan kemiringan yang presisi. Menjamin integritas dokumen elektronik Anda melalui teknologi enkripsi yang aman, memberikan kekuatan hukum yang setara dengan tanda tangan di atas kertas.", 
    bgType: 'matrix', 
    tag: "Rapid Response", 
    Icon: Signature, 
    status: "Sistem Tanda Tangan Digital",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 7, 
    short: "PALM_VEIN", 
    title: "Palm Vein", 
    subtitle: "OTENTIKASI BIOMETRIK TELAPAK TANGAN TANPA SENTUH", 
    description: "Teknologi otentikasi mutakhir yang memetakan pola pembuluh darah telapak tangan. Karena pola vena berada di dalam tubuh, sistem ini menawarkan tingkat keamanan tertinggi yang mustahil dipalsukan, memberikan perlindungan maksimal untuk akses aset paling kritis", 
    bgType: 'grid', 
    tag: "Infrastructure", 
    Icon: Hand, 
    status: "Sistem Biometrik Palm Vein",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800" 
  },
  { 
    id: 8, 
    short: "Face_Recognition", 
    title: "Face Recognition", 
    subtitle: "INTERAKSI NIRKABEL INSTAN BERBASIS NFC", 
    description: "Sederhanakan transaksi dan manajemen akses dengan teknologi Near Field Communication (NFC). Memungkinkan pertukaran data nirkabel yang aman untuk sistem pembayaran cashless, kontrol akses gedung, hingga verifikasi identitas secara real-time.", 
    bgType: 'pulse', 
    tag: "Perimeter Sec", 
    Icon: Nfc, 
    status: "Sistem Pengenalan Wajah",
    image: "https://www.tnitech.co/_next/image?url=%2Fimages%2Fhome%2Ffr.gif&w=3840&q=75" 
  }
];